---
- hosts: all
  user: provision
  sudo: true
  vars_files:
    - vars/defaults.yml

  roles:
    - webserver
    - database
    - elasticsearch

  # handlers: 
  #   - name: Restart puma
  #     action: service name=puma state=restarted