---
- name: upgrade
  action: apt update_cache=yes upgrade=yes

- name: Install app dependencies 
  action: apt pkg={{item}} state=installed
  with_items:
    - libpq-dev
    - nodejs
    - imagemagick
  tags: package

- name: Create deployment user
  user: name=deploy comment="Application deployment user"

- authorized_key: user=deploy key='{{ lookup('file', '~/.ssh/id_rsa.pub') }}'

- name: Create deployment directory
  file: path={{deploy_directory}} owner=deploy group=deploy state=directory

- name: Create shared directory
  file: path={{deploy_directory}}/shared owner=deploy group=deploy state=directory

- name: Make shared subdirectories
  file: path={{deploy_directory}}/shared/{{item}} group=deploy owner=deploy state=directory
  with_items:
    - tmp
    - log
    - public
    - bundle
    - bin
    - config
    - vendor
  tags: shared

- name: Install database.yml
  template: src=database.yml.j2 dest={{deploy_directory}}/shared/config/database.yml force=yes mode=755 owner=deploy