source 'https://rubygems.org'

gem 'rails', '4.0.2'

gem 'pg'

# Front end
gem 'sass-rails'
gem 'bootstrap-sass'
gem 'bourbon'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'

# Admin
gem 'activeadmin', github: 'gregbell/active_admin'

# Blog
# gem 'bloggy', :github => 'jesseadams/bloggy', :branch => 'fix-rake-generate'
# gem 'jekyll-slim'

# Performance
gem 'actionpack-page_caching'
# gem 'redis'

group :production do 
  gem 'unicorn'
end

group :development do 
  gem 'capistrano', '~> 2.15', require: false
  gem 'capistrano-ext', require: false
  gem 'capistrano-unicorn', require: false
  gem 'capistrano-remote-cache-with-project-root'#, require: false
  gem 'cape', require: false
end

# Static pages
gem 'high_voltage'

gem 'slim'
gem 'redcarpet'

# gem 'whenever'

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'