development:
  adapter: postgresql
  database: datrepo_site
  user: kyle
  password: 
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: datrepo_test
  user: kyle
  password:
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: app_datrepo
  user: deploy
  password: datrepo_db_password
  pool: 5
  timeout: 5000
